# Your Name or Company
title: Richard Hatcher

# Description of your website. This is used for social sharing.
description:  The beautiful website of artist, poet, craftsperson, and cyclist, Richard Hatcher

# A brief blurb about yourself
content: Heyyo! I would tailor this message based on the intent of the user but I have no idea why anybody is on this site. But hey, welcome nonetheless. I hope that you are having a blast today!

# Add your social links
social:
  - platform: github
    url: https://github.com/RichardHatcher
  - platform: facebook
    url: https://www.facebook.com/richard.hatcher.9469
  - platform: twitter
    url: https://twitter.com/My_Vroom
  - platform: linkedin
    url: https://www.linkedin.com/in/richard-hatcher-93a6343/

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni"
markdown: kramdown
sharing_image: share.jpg
#google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
